version: '3'
services:
  backend:
    image: booklendjava
    ports:
      - "8080:8080"

  frontend:
    image: booklendreact
    ports:
      - "5173:5173"
    depends_on:
      - backend

networks:
  spring-boot-network:
    driver: bridge
